#!/usr/bin/with-contenv sh
# English: Start Audiobookshelf (Node.js) as user 'abc' using node index.js.
# Deutsch: Startet Audiobookshelf (Node.js) als Benutzer 'abc' mit node index.js.

cd /app

export LANG="en_US.UTF-8"
export LANGUAGE="en_US:de_DE"
export LC_ALL="en_US.UTF-8"

exec su-exec abc:abc node index.js
