# Docker Compose file for Audiobookshelf
# No version needed for modern Docker Compose

services:
  audiobookshelf:
    image: ${IMAGE_NAME:-mildman1848/audiobookshelf}:${IMAGE_TAG:-latest}
    container_name: audiobookshelf
    hostname: audiobookshelf
    restart: unless-stopped

    # Security hardening (basic)
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID

    # Network configuration
    ports:
      - "${HOST:-127.0.0.1}:${EXTERNAL_PORT:-13378}:80"

    # Environment configuration
    environment:
      # LinuxServer.io base variables
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - UMASK=${UMASK:-022}

      # Audiobookshelf core configuration (SQLite3 as default)
      - CONFIG_PATH=${CONFIG_PATH:-/config}
      - METADATA_PATH=${METADATA_PATH:-/metadata}
      - BACKUP_PATH=${BACKUP_PATH:-/config/backups}

      # Application settings
      - SOURCE=${SOURCE:-docker}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=${NODE_ENV:-production}

      # Security configuration
      - CORS_ENABLED=${CORS_ENABLED:-0}
      - DISABLE_SSRF=${DISABLE_SSRF:-0}
      - ALLOW_IFRAMES=${ALLOW_IFRAMES:-0}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-true}
      - SESSION_COOKIE_HTTP_ONLY=${SESSION_COOKIE_HTTP_ONLY:-true}

      # Binary paths
      - FFMPEG_PATH=${FFMPEG_PATH:-/usr/bin/ffmpeg}
      - FFPROBE_PATH=${FFPROBE_PATH:-/usr/bin/ffprobe}

      # Performance settings
      - MAX_CONCURRENT_SCANS=${MAX_CONCURRENT_SCANS:-1}
      - SCANNER_DISABLE_WATCHER=${SCANNER_DISABLE_WATCHER:-false}

      # Feature flags
      - ENABLE_EXPERIMENTAL_FEATURES=${ENABLE_EXPERIMENTAL_FEATURES:-false}
      - ENABLE_FILE_WATCHER=${ENABLE_FILE_WATCHER:-true}
      - SCANNER_FIND_COVERS=${SCANNER_FIND_COVERS:-true}

      # Optional: FILE__ prefix secrets support
      - FILE__JWT_SECRET=/run/secrets/audiobookshelf_jwt_secret

    # Volume mounts
    volumes:
      - ${CONFIG_PATH:-./config}:/config
      - ${AUDIOBOOKS_PATH:-./data/audiobooks}:/audiobooks
      - ${PODCASTS_PATH:-./data/podcasts}:/podcasts
      - ${METADATA_PATH:-./data/metadata}:/metadata
      - ${LOGS_PATH:-./logs}:/config/logs

    # Optional: Docker secrets support
    secrets:
      - audiobookshelf_jwt_secret

    # Health check (process-based for security)
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep -v grep | grep audiobookshelf || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Labels for better organization
    labels:
      - "org.opencontainers.image.title=audiobookshelf"
      - "org.opencontainers.image.description=Audiobookshelf - Self-hosted audiobook and podcast server with S6 Overlay"
      - "org.opencontainers.image.vendor=Mildman1848"

# Docker secrets (optional)
secrets:
  audiobookshelf_jwt_secret:
    file: ${SECRETS_PATH:-./secrets}/audiobookshelf_jwt_secret.txt

# Networks (optional)
networks:
  default:
    name: ${NETWORK_NAME:-audiobookshelf_network}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET:-172.20.0.0/16}